language: R
cache: packages
notifications:
  email: false
dist: trusty
env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
r_packages:
  - covr
  - devtools
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
