language: R
cache: packages
notifications:
  email: false
dist: trusty
env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
r_packages:
  - covr
  - devtools
sudo: required

after_success:
  - Rscript -e 'library(covr); codecov()'
